[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.25"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

optimizer = true
optimizer_runs = 20_000

rpc_url = "https://rpc.testnet.sova.io"

no_match_coverage = "(script/|test/|mocks/)"