[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["solady/=lib/solady/src/"]
solc = "0.8.25"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

optimizer = true
optimizer_runs = 200

rpc_url = "https://base.drpc.org"

no_match_coverage = "(script/|test/|mocks/)"

[rpc_endpoints]
base-sepolia = "https://base-sepolia.drpc.org"
base = "https://base.drpc.org"

[etherscan]
base-sepolia = { key = "${ETHERSCAN_API_KEY}" }
base = { key = "${ETHERSCAN_API_KEY}" }
